apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: powerapp-backend
  name: powerapp-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: powerapp-backend
    spec:
      containers:
      - name: powerapp-backend
        image: sighup/kubeprimer-backend
        env:
        - name: MONGO_HOST
          value: powerapp-mongodb-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always
